import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RENDER = ROOT / "scripts" / "render_study.py"
FIGURES = ROOT / "scripts" / "figure_assets.py"


class VisualSystemTests(unittest.TestCase):
    def test_theme_contains_learning_readability_defaults(self):
        css = (ROOT / "assets" / "study-theme.css").read_text(encoding="utf-8")
        self.assertIn("--study-body-leading: 1.72", css)
        self.assertIn("--study-measure: 42rem", css)
        self.assertIn("--study-gutter: 8rem", css)
        self.assertIn("--study-wide: 52rem", css)
        self.assertIn("--study-paper-width: 66rem", css)
        self.assertIn('"Source Serif 4"', css)
        self.assertIn('"IBM Plex Sans"', css)
        self.assertIn("data-study-theme=\"dark\"", css)
        self.assertIn("print-color-adjust", css)
        self.assertIn("semantic rails", css.lower())
        self.assertIn("--study-paper: #fbf9f4", css)
        self.assertNotIn("linear-gradient", css)
        self.assertIn("--shadow-paper: none", css)
        self.assertIn("contemporary technical manual", (ROOT / "design" / "README.md").read_text(encoding="utf-8"))
        self.assertIn(".book-running-line", css)
        self.assertIn(".section-head", css)
        self.assertIn(".row > .mark", css)
        self.assertIn("@bottom-center", css)

    def test_generated_theme_matches_design_sources_exactly(self):
        parts = ["tokens.css", "typography.css", "layout.css", "components.css", "figures.css", "print.css"]
        body = ["/* GENERATED by scripts/build_design.py — do not edit directly. */\n"]
        for name in parts:
            body.append(f"\n/* --- {name} --- */\n")
            body.append((ROOT / "design" / name).read_text(encoding="utf-8").rstrip() + "\n")
        expected = "".join(body)
        actual = (ROOT / "assets" / "study-theme.css").read_text(encoding="utf-8")
        self.assertEqual(actual, expected)

    def test_design_sources_and_generated_theme_exist(self):
        for rel in (
            "design/tokens.css",
            "design/typography.css",
            "design/layout.css",
            "design/components.css",
            "design/figures.css",
            "design/print.css",
            "scripts/build_design.py",
        ):
            self.assertTrue((ROOT / rel).is_file(), rel)
        self.assertTrue((ROOT / "skills-src" / "study-design" / "SKILL.md").is_file())
        self.assertTrue((ROOT / "skills-src" / "study-design-reviewer" / "SKILL.md").is_file())

    def test_renderer_semantic_gutter_callouts_and_visible_recall(self):
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            md = td / "u1.md"
            out = td / "u1.html"
            md.write_text(
                """# Unidad 1\n\n## Concepto\n\nTexto **clave**.\n\n> [!DEFINITION] Variable\n> Un dato que puede cambiar.\n\n> [!WARNING] Precondición no es validación\n> No confundas una garantía con una comprobación.\n\n> [!EXAM] Formato confirmado para el final\n> Se evalúa con el formato indicado por la cátedra.\n\n> [!RECALL] Sin mirar\n> Explicá qué es una variable.\n""",
                encoding="utf-8",
            )
            cp = subprocess.run(
                [sys.executable, str(RENDER), str(md), str(out), "--kind", "summary", "--course", "Programación I", "--scope", "Unidad 1", "--check"],
                cwd=ROOT,
                text=True,
                capture_output=True,
            )
            self.assertEqual(cp.returncode, 0, cp.stdout + cp.stderr)
            page = out.read_text(encoding="utf-8")
            self.assertIn('class="callout definition"', page)
            self.assertIn('class="callout recall"', page)
            self.assertNotIn('<details class="callout recall">', page)
            self.assertIn('class="callout-body"', page)
            self.assertIn('<div class="callout-title">Definición</div>', page)
            self.assertIn('<p class="term">Variable</p>', page)
            self.assertIn('<div class="callout-title">Cuidado</div>', page)
            self.assertIn('<p class="term">Precondición no es validación</p>', page)
            self.assertIn('<div class="callout-title">Para evaluación</div>', page)
            self.assertIn('<p class="term">Formato confirmado para el final</p>', page)
            self.assertIn('<div class="callout-title">Recuperación</div>', page)
            self.assertIn('<p class="term">Sin mirar</p>', page)
            self.assertIn('class="prompt"', page)
            self.assertIn('class="hint"', page)
            self.assertNotIn('class="toc"', page)
            self.assertIn("Texto <strong>clave</strong>", page)
            self.assertIn('class="book-running-line"', page)
            self.assertIn('class="book-course">Programación I</span>', page)
            self.assertIn('class="study-header"><div class="mark">Capítulo 1</div>', page)
            self.assertIn('class="section-head"><div class="num"></div><h2', page)
            self.assertIn('fonts.googleapis.com', page)

    def test_figure_machine_commands_keep_stdout_as_parseable_json(self):
        cp = subprocess.run(
            [sys.executable, str(FIGURES), "preflight"],
            cwd=ROOT, text=True, capture_output=True,
        )
        self.assertEqual(cp.returncode, 0, cp.stdout + cp.stderr)
        payload = json.loads(cp.stdout)
        self.assertIn("pdf_visuals", payload)
        self.assertNotIn("WARNING", cp.stdout.upper())

    def test_textbook_frontmatter_strips_repeated_scope_from_visible_title(self):
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            md = td / "u1.md"
            out = td / "u1.html"
            md.write_text("# Unidad 1: Conceptos básicos\n\nTexto.\n", encoding="utf-8")
            cp = subprocess.run(
                [sys.executable, str(RENDER), str(md), str(out), "--kind", "summary", "--course", "Programación I", "--scope", "Unidad 1", "--check"],
                cwd=ROOT,
                text=True,
                capture_output=True,
            )
            self.assertEqual(cp.returncode, 0, cp.stdout + cp.stderr)
            page = out.read_text(encoding="utf-8")
            self.assertIn('<h1 id="unidad-1-conceptos-básicos">Conceptos básicos</h1>', page)
            self.assertIn('<div class="mark">Capítulo 1</div>', page)
            self.assertIn('Resumen · Unidad 1', page)

    def test_guide_keeps_quiet_toc_and_progress_when_long_enough(self):
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            md = td / "guide.md"
            out = td / "guide.html"
            md.write_text("# Guía\n\n## Uno\nTexto.\n\n## Dos\nTexto.\n\n## Tres\nTexto.\n\n## Cuatro\nTexto.\n", encoding="utf-8")
            cp = subprocess.run([sys.executable, str(RENDER), str(md), str(out), "--kind", "guide", "--check"], cwd=ROOT, text=True, capture_output=True)
            self.assertEqual(cp.returncode, 0, cp.stdout + cp.stderr)
            page = out.read_text(encoding="utf-8")
            self.assertIn('class="study-grid with-toc"', page)
            self.assertIn('class="toc"', page)
            self.assertIn('href="#uno"', page)
            self.assertIn('class="reading-progress"', page)
            self.assertIn("d.scrollTop / max", page)

    def test_figures_are_numbered_plated_and_tables_use_overflow_wrapper(self):
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            (td / "x.png").write_bytes(b"png")
            md = td / "x.md"
            out = td / "x.html"
            md.write_text("# X\n\n![Diagrama](x.png \"Jerarquía de memoria\")\n\n| A | B |\n| --- | --- |\n| 1 | 2 |\n", encoding="utf-8")
            cp = subprocess.run([sys.executable, str(RENDER), str(md), str(out), "--kind", "summary", "--check"], cwd=ROOT, text=True, capture_output=True)
            self.assertEqual(cp.returncode, 0, cp.stdout + cp.stderr)
            page = out.read_text(encoding="utf-8")
            self.assertIn('class="table-scroll"', page)
            self.assertIn('class="plate"', page)
            self.assertIn('counter(study-figure)', (ROOT / "assets" / "study-theme.css").read_text(encoding="utf-8"))
            self.assertIn('<figcaption><span>Jerarquía de memoria</span></figcaption>', page)

    def test_reference_design_keeps_lede_inside_chapter_header_and_captions_apparatus(self):
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            md = td / "x.md"
            out = td / "x.html"
            md.write_text(
                """# Título de capítulo

Una bajada editorial.

## Sección

```text
leer dato
```
<!-- caption: El dato entra al algoritmo. -->

| A | B |
| --- | --- |
| 1 | 2 |
<!-- caption: Comparación mínima. -->
""",
                encoding="utf-8",
            )
            cp = subprocess.run(
                [sys.executable, str(RENDER), str(md), str(out), "--kind", "summary", "--course", "Materia", "--scope", "Unidad 2", "--check"],
                cwd=ROOT,
                text=True,
                capture_output=True,
            )
            self.assertEqual(cp.returncode, 0, cp.stdout + cp.stderr)
            page = out.read_text(encoding="utf-8")
            header_start = page.index('<header class="study-header">')
            header_end = page.index('</header>', header_start)
            header = page[header_start:header_end]
            self.assertIn('<div class="mark">Capítulo 2</div>', header)
            self.assertIn('class="study-lede"', header)
            self.assertIn('class="code-caption"', page)
            self.assertIn('class="table-caption"', page)
            css = (ROOT / "assets" / "study-theme.css").read_text(encoding="utf-8")
            self.assertIn('counter(study-code)', css)

    def test_renderer_rejects_broken_local_image_in_check_mode(self):
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            md = td / "x.md"
            out = td / "x.html"
            md.write_text("# X\n\n![Diagrama](missing.png)\n", encoding="utf-8")
            cp = subprocess.run([sys.executable, str(RENDER), str(md), str(out), "--check"], cwd=ROOT, text=True, capture_output=True)
            self.assertNotEqual(cp.returncode, 0)
            self.assertIn("image-missing:missing.png", cp.stdout)

    def test_renderer_rebases_images_from_source_folder_to_html_folder(self):
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            source_dir = td / "resumenes" / "_source"
            asset_dir = td / "assets" / "figures"
            source_dir.mkdir(parents=True)
            asset_dir.mkdir(parents=True)
            (asset_dir / "x.png").write_bytes(b"png")
            md = source_dir / "u1.md"
            out = td / "resumenes" / "u1.html"
            md.write_text("# X\n\n![Figura](../../assets/figures/x.png)\n", encoding="utf-8")
            cp = subprocess.run([sys.executable, str(RENDER), str(md), str(out), "--check"], cwd=ROOT, text=True, capture_output=True)
            self.assertEqual(cp.returncode, 0, cp.stdout + cp.stderr)
            page = out.read_text(encoding="utf-8")
            self.assertIn('src="../assets/figures/x.png"', page)

    def test_figure_registry_exists_in_course_template(self):
        data = json.loads((ROOT / "materias" / "_plantilla" / "conocimiento" / "figures.json").read_text(encoding="utf-8"))
        self.assertEqual(data["version"], 2)
        self.assertEqual(data["figures"], {})

    def test_visual_dependency_is_explicit_and_optional(self):
        req = (ROOT / "requirements-visual.txt").read_text(encoding="utf-8")
        self.assertIn("PyMuPDF", req)
        help_cp = subprocess.run([sys.executable, str(FIGURES), "--help"], cwd=ROOT, text=True, capture_output=True)
        self.assertEqual(help_cp.returncode, 0)


    def test_captions_allow_blank_lines_but_orphans_fail_check(self):
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            md = td / "x.md"
            out = td / "x.html"
            md.write_text(
                """# X

| A | B |
| --- | --- |
| 1 | 2 |

<!-- caption: Tabla con aire antes del caption. -->

```text
leer dato
```

<!-- caption: Código con aire antes del caption. -->
""",
                encoding="utf-8",
            )
            cp = subprocess.run([sys.executable, str(RENDER), str(md), str(out), "--kind", "summary", "--check"], cwd=ROOT, text=True, capture_output=True)
            self.assertEqual(cp.returncode, 0, cp.stdout + cp.stderr)
            page = out.read_text(encoding="utf-8")
            self.assertIn("Tabla con aire antes del caption.", page)
            self.assertIn("Código con aire antes del caption.", page)
            self.assertNotIn("<!-- caption:", page)

            md.write_text("# X\n\n<!-- caption: Huérfano. -->\n\nTexto.\n", encoding="utf-8")
            cp = subprocess.run([sys.executable, str(RENDER), str(md), str(out), "--kind", "summary", "--check"], cwd=ROOT, text=True, capture_output=True)
            self.assertNotEqual(cp.returncode, 0)
            self.assertIn("orphan-caption", cp.stdout + cp.stderr)


if __name__ == "__main__":
    unittest.main()
