#!/usr/bin/env python3
from __future__ import annotations
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARTS = [
    ROOT / "design" / "tokens.css",
    ROOT / "design" / "typography.css",
    ROOT / "design" / "layout.css",
    ROOT / "design" / "components.css",
    ROOT / "design" / "figures.css",
    ROOT / "design" / "print.css",
]
OUT = ROOT / "assets" / "study-theme.css"


def build() -> str:
    body = ["/* GENERATED by scripts/build_design.py — do not edit directly. */\n"]
    for p in PARTS:
        body.append(f"\n/* --- {p.name} --- */\n")
        body.append(p.read_text(encoding="utf-8").rstrip() + "\n")
    text = "".join(body)
    OUT.write_text(text, encoding="utf-8")
    return hashlib.sha256(text.encode()).hexdigest()

if __name__ == "__main__":
    print(build())
